#!/usr/bin/env bash

set -e
set -i

shift $((OPTIND - 1))

pattern=$1
replacement=$2

if [[ $3 = "" ]]; then
  glob=./*
else
  glob=$3
fi

git ls-files $glob | \
 xargs -L 1 file | \
 grep 'text'  | \
 awk -F: '{print $1}' | \
 xargs -L 1 sed -i '' s/$pattern/$replacement/g
